---
- name: Test VM creation
  hosts: localhost
  tasks:
    - import_role:
        name: kamaki-ansibe-role
    - name: Authenticate cloud
      cloud:
        ca_certs='/etc/ssl/certs/ca-certificates.crt'
        url='https://astakos.okeanos-knossos.grnet.gr/identity/v2.0'
        token='MY-SYNNEFO-TOKEN'
        project_id='MY-PROJECT'
      register: cloud
    - name: Create PPK
      keypair:
        cloud={{ cloud }}
        # If the name does not exist, it will be created
        # If no name is given, a name will be generated
        name='My keypair'
      register: ppk
    - name: Save private key
      copy:
        # Only if this is a new key
        content={{ ppk.keypair.private_key }}
        dest=/tmp/my_private.key
      register: saved_key
    - name: Create private network
      network:
        cloud={{ cloud }}
        name='my temp net'
        dhcp=True
        cidr='192.168.0.0/24'
      register: pnet
    - name: Create IP
      public_ip:
        cloud={{ cloud }}
        # If not specified, a new one will be created
        # address='83.212.73.217'
      register: ip
    - name: Create VM
      server:
        cloud={{ cloud }}
        name='My temp VM'
        flavor_id=260
        image_id='051669a1-835a-4e01-995e-1d21c74839c7'
        public_ip={{ ip }}
        network={{ pnet }}
        keypair={{ ppk }}
      register: vm
    - name: Free IP
      public_ip:
        state=absent
        cloud={{ cloud }}
        id={{ ip.ip.id }}
      register: ip_deleted
    - name: Destroy VM
      server:
        state=absent
        cloud={{ cloud }}
        id={{ vm.server.id }}
      register: vm_deleted
    - name: Destroy private network
      network:
        state=absent
        cloud={{ cloud }}
        id={{ pnet.network.id }}
      register: pnet_deleted
    - name: Delete keypair
      keypair:
        state=absent
        cloud={{ cloud }}
        name={{ ppk.keypair.name }}
      register: ppk_deleted
